[Controls]
Style=Material             ;
FallbackStyle=Material

[Universal]
Theme=Light
Accent=#002878              ; 设置强调色为橙色
Foreground=#3A3B3B        ; 设置前景色
Background=#D9D9D9           ; 设置背景色

[Material]
Theme=Light
Variant=Dense
Accent=#406FD8
Primary=#002878
Foreground=#3A3B3B        ; 设置前景色
Background=#f4f4f4           ; 设置背景色